name: Voltedge MVP CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run tests inside API container
        run: docker compose exec -T api pytest tests

      - name: Stop containers
        if: always()
        run: docker compose down